workflows:
  flutter-app:
    name: Build and Deploy Flutter App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        BUNDLE_ID: com.example.yourapp
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up dependencies
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=ExportOptions.plist
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth:
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          key_identifier: $APP_STORE_CONNECT_KEY_IDENTIFIER
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
